<?php
namespace App\Http\Controllers;
use App\Http\Requests\StorePengaduanRequest; use App\Http\Requests\UpdatePengaduanRequest; use App\Models\Pengaduan; use App\Models\User; use Illuminate\Http\Request; use Illuminate\Support\Facades\Storage; use Illuminate\Support\Str;
class PengaduanController extends Controller {
 private function number(): string { do { $number='PGD-'.now()->format('Ymd').'-'.strtoupper(Str::random(6)); } while(Pengaduan::where('nomor_pengaduan',$number)->exists()); return $number; }
 public function index(Request $request){ $this->authorize('viewAny',Pengaduan::class); $query=Pengaduan::with('user'); if($request->user()->isCustomer()) $query->where('user_id',$request->user()->id); if($request->filled('search')) $query->where(fn($q)=>$q->where('nomor_pengaduan','like','%'.$request->search.'%')->orWhereHas('user',fn($u)=>$u->where('name','like','%'.$request->search.'%'))); if($request->filled('date')) $query->whereDate('created_at',$request->date); return view('pengaduans.index',['pengaduans'=>$query->latest()->paginate(10)->withQueryString()]); }
 public function create(){ $this->authorize('create',Pengaduan::class); return view('pengaduans.form',['pengaduan'=>new Pengaduan(),'users'=>request()->user()->isAdmin()?User::orderBy('name')->get():null]); }
 public function store(StorePengaduanRequest $request){ $this->authorize('create',Pengaduan::class); $data=$request->safe()->except('foto'); $owner=request()->user()->isAdmin() && $request->integer('user_id') ? User::findOrFail($request->integer('user_id')) : request()->user(); $pengaduan=new Pengaduan($data); $pengaduan->user_id=$owner->id; $pengaduan->nomor_pengaduan=$this->number(); if($request->hasFile('foto')) $pengaduan->foto=$request->file('foto')->store('pengaduans','public'); $pengaduan->save(); return redirect()->route('pengaduans.show',$pengaduan)->with('success','Pengaduan berhasil dibuat.'); }
 public function show(Pengaduan $pengaduan){ $this->authorize('view',$pengaduan); return view('pengaduans.show',compact('pengaduan')); }
 public function edit(Pengaduan $pengaduan){ $this->authorize('update',$pengaduan); return view('pengaduans.form',['pengaduan'=>$pengaduan,'users'=>User::orderBy('name')->get()]); }
 public function update(UpdatePengaduanRequest $request, Pengaduan $pengaduan){ $this->authorize('update',$pengaduan); $pengaduan->fill($request->safe()->except('foto')); if($request->hasFile('foto')) { if($pengaduan->foto) Storage::disk('public')->delete($pengaduan->foto); $pengaduan->foto=$request->file('foto')->store('pengaduans','public'); } $pengaduan->save(); return redirect()->route('pengaduans.show',$pengaduan)->with('success','Data berhasil diperbarui.'); }
 public function destroy(Pengaduan $pengaduan){ $this->authorize('delete',$pengaduan); if($pengaduan->foto) Storage::disk('public')->delete($pengaduan->foto); $pengaduan->delete(); return redirect()->route('pengaduans.index')->with('success','Data berhasil dihapus.'); }
}
